kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "go-encrypt-build"
spec:
  source:
    dockerfile: |-
      FROM scratch

      COPY main /app/
      WORKDIR /app
      CMD ["./main"]
    images:
    - from:
        kind: "ImageStreamTag"
        name: "go-encrypt-exe:latest"
      paths:
      - sourcePath: "/app/main"
        destinationDir: "."
  triggers:
  - imageChange: {}
    type: "ImageChange"
  output:
    to:
      kind: "ImageStreamTag"
      name: "go-encrypt:latest"